import React, {useMemo, useState} from 'react';
import {Alert, FlatList, Pressable, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, View} from 'react-native';

type AccountRecord = {id: string; client: string; project: string; platform: string; accountName: string; email: string; username: string; password: string; status: 'Active' | 'Paused' | 'Archived'; notes: string};
const initialRecords: AccountRecord[] = [{id: '1', client: 'Example Client', project: 'Example Campaign', platform: 'Instagram', accountName: '@examplebrand', email: 'social@example.com', username: 'examplebrand', password: '', status: 'Active', notes: 'Replace this sample record with a real project.'}];
const emptyDraft: Omit<AccountRecord, 'id'> = {client: '', project: '', platform: 'Instagram', accountName: '', email: '', username: '', password: '', status: 'Active', notes: ''};

export default function App() {
  const [records, setRecords] = useState<AccountRecord[]>(initialRecords);
  const [query, setQuery] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [draft, setDraft] = useState(emptyDraft);
  const filteredRecords = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return records; return records.filter(r => [r.client, r.project, r.platform, r.accountName, r.email].join(' ').toLowerCase().includes(q)); }, [query, records]);
  function updateDraft(field: keyof typeof emptyDraft, value: string) { setDraft(current => ({...current, [field]: value})); }
  function addRecord() { if (!draft.client.trim() || !draft.platform.trim() || !draft.accountName.trim()) { Alert.alert('Missing information', 'Client, platform, and account name are required.'); return; } setRecords(current => [...current, {...draft, id: Date.now().toString(), client: draft.client.trim(), project: draft.project.trim(), platform: draft.platform.trim(), accountName: draft.accountName.trim(), email: draft.email.trim(), username: draft.username.trim(), notes: draft.notes.trim()}]); setDraft(emptyDraft); setShowForm(false); }
  function archiveRecord(id: string) { setRecords(current => current.map(record => record.id === id ? {...record, status: 'Archived'} : record)); }
  function renderRecord({item}: {item: AccountRecord}) { return <View style={styles.card}><View style={styles.cardHeader}><View style={styles.cardHeading}><Text style={styles.platform}>{item.platform}</Text><Text style={styles.accountName}>{item.accountName}</Text></View><Text style={[styles.status, item.status === 'Archived' && styles.archived]}>{item.status}</Text></View><Text style={styles.meta}>{item.client}{item.project ? ` • ${item.project}` : ''}</Text>{item.email ? <Text style={styles.detail}>Email: {item.email}</Text> : null}{item.username ? <Text style={styles.detail}>Username: {item.username}</Text> : null}{item.notes ? <Text style={styles.notes}>{item.notes}</Text> : null}{item.status !== 'Archived' ? <Pressable style={styles.archiveButton} onPress={() => archiveRecord(item.id)}><Text style={styles.archiveButtonText}>Archive</Text></Pressable> : null}</View>; }
  return <SafeAreaView style={styles.safeArea}><StatusBar barStyle="dark-content" /><View style={styles.container}><View style={styles.header}><View><Text style={styles.eyebrow}>OFFLINE REGISTER</Text><Text style={styles.title}>Account Register</Text></View><Pressable style={styles.addButton} onPress={() => setShowForm(current => !current)}><Text style={styles.addButtonText}>{showForm ? 'Close' : '+ Add'}</Text></Pressable></View>{showForm ? <ScrollView style={styles.form} keyboardShouldPersistTaps="handled"><Text style={styles.sectionTitle}>New account record</Text><Field label="Client / person *" value={draft.client} onChangeText={value => updateDraft('client', value)} placeholder="Example Client" /><Field label="Project" value={draft.project} onChangeText={value => updateDraft('project', value)} placeholder="Example Campaign" /><Field label="Platform *" value={draft.platform} onChangeText={value => updateDraft('platform', value)} placeholder="Instagram" /><Field label="Account name *" value={draft.accountName} onChangeText={value => updateDraft('accountName', value)} placeholder="@brand or page name" /><Field label="Email" value={draft.email} onChangeText={value => updateDraft('email', value)} placeholder="login@example.com" keyboardType="email-address" /><Field label="Username" value={draft.username} onChangeText={value => updateDraft('username', value)} placeholder="Optional username" /><Field label="Password (reserved for later)" value={draft.password} onChangeText={value => updateDraft('password', value)} placeholder="Not stored securely in this starter" secureTextEntry /><Field label="Notes" value={draft.notes} onChangeText={value => updateDraft('notes', value)} placeholder="Instructions or context" multiline /><Pressable style={styles.saveButton} onPress={addRecord}><Text style={styles.saveButtonText}>Save record</Text></Pressable></ScrollView> : <><TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search clients, projects, platforms..." placeholderTextColor="#87909c" clearButtonMode="while-editing" /><Text style={styles.summary}>{filteredRecords.length} record{filteredRecords.length === 1 ? '' : 's'}</Text><FlatList data={filteredRecords} keyExtractor={item => item.id} renderItem={renderRecord} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>No records match your search.</Text>} /></>}</View></SafeAreaView>;
}

type FieldProps = React.ComponentProps<typeof TextInput> & {label: string};
function Field({label, ...props}: FieldProps) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} style={[styles.input, props.multiline && styles.multiline]} placeholderTextColor="#87909c" /></View>; }
const styles = StyleSheet.create({safeArea: {flex: 1, backgroundColor: '#f5f7fb'}, container: {flex: 1, paddingHorizontal: 20}, header: {paddingTop: 22, paddingBottom: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, eyebrow: {color: '#5267d9', fontSize: 11, fontWeight: '800', letterSpacing: 1.5}, title: {color: '#172033', fontSize: 28, fontWeight: '800', marginTop: 5}, addButton: {backgroundColor: '#5267d9', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 11}, addButtonText: {color: '#fff', fontWeight: '800'}, search: {backgroundColor: '#fff', borderColor: '#e0e5ee', borderWidth: 1, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15}, summary: {color: '#687386', fontSize: 13, marginTop: 15, marginBottom: 7}, list: {paddingBottom: 30}, card: {backgroundColor: '#fff', borderRadius: 16, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: '#e6eaf1'}, cardHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start'}, cardHeading: {flex: 1}, platform: {color: '#5267d9', fontWeight: '800', fontSize: 13, textTransform: 'uppercase', letterSpacing: 0.5}, accountName: {color: '#172033', fontWeight: '800', fontSize: 18, marginTop: 3}, status: {color: '#287a51', backgroundColor: '#e5f5ec', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 20, fontSize: 12, fontWeight: '700'}, archived: {color: '#687386', backgroundColor: '#edf0f4'}, meta: {color: '#4e596b', marginTop: 12, fontWeight: '600'}, detail: {color: '#687386', marginTop: 6}, notes: {color: '#687386', marginTop: 10, lineHeight: 20}, archiveButton: {alignSelf: 'flex-start', marginTop: 14, paddingVertical: 5}, archiveButtonText: {color: '#b34848', fontWeight: '700'}, empty: {textAlign: 'center', color: '#687386', marginTop: 40}, form: {flex: 1}, sectionTitle: {fontSize: 20, color: '#172033', fontWeight: '800', marginBottom: 16}, field: {marginBottom: 14}, label: {fontSize: 13, color: '#4e596b', fontWeight: '700', marginBottom: 7}, input: {backgroundColor: '#fff', borderColor: '#e0e5ee', borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 11, color: '#172033', fontSize: 15}, multiline: {minHeight: 90, textAlignVertical: 'top'}, saveButton: {backgroundColor: '#5267d9', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 4, marginBottom: 30}, saveButtonText: {color: '#fff', fontWeight: '800', fontSize: 16}});
