import React, {useState} from 'react';
import {Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {AccountRecord, EMPTY_VALUE_LABEL, RegisterData} from '../domain/models';
import {nativeStore} from '../services/nativeStore';
import {ContextMenu} from '../components/ContextMenu';

const date = (value?: string) => value ? new Date(value).toLocaleString([], {day: 'numeric', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit'}) : EMPTY_VALUE_LABEL;
const valueOrEmpty = (value?: string) => value || EMPTY_VALUE_LABEL;

export function AccountDetailScreen({record, data, onBack, onEdit, onDelete, onUpdate, onOpenClient, onOpenProject, onOpenPlatform}: {record: AccountRecord; data: RegisterData; onBack: () => void; onEdit: () => void; onDelete: () => void; onUpdate: (changes: Partial<AccountRecord>) => Promise<void>; onOpenClient?: (id: string) => void; onOpenProject?: (id: string) => void; onOpenPlatform?: (id: string) => void}) {
  const [secret, setSecret] = useState('');
  const [showMore, setShowMore] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const clients = data.clients.filter(item => record.clientIds?.includes(item.id) || item.id === record.clientId);
  const projects = data.projects.filter(item => record.projectIds?.includes(item.id) || item.id === record.projectId);
  const platform = data.platforms.find(item => item.id === record.platformId);
  const category = data.categories.find(item => item.id === record.categoryId)?.name;
  const openLink = async (url?: string) => { if (!url) return; if (await Linking.canOpenURL(url)) await Linking.openURL(url); else Alert.alert('Unable to open link', url); };
  const archiveOrRestore = () => { if (record.status === 'archived') return onUpdate({status: 'active'}); Alert.alert('Archive account?', 'The record will remain stored and can be restored later.', [{text: 'Cancel'}, {text: 'Archive', onPress: () => onUpdate({status: 'archived'})}]); };
  return <ScrollView contentContainerStyle={styles.page}>
    <View style={styles.header}><Pressable onPress={onBack}><Text style={styles.back}>‹ Account register</Text></Pressable><Pressable style={styles.moreButton} onPress={() => setMenuOpen(true)}><Text style={styles.moreText}>•••</Text></Pressable></View>
    <Text style={styles.eyebrow}>{platform?.name || EMPTY_VALUE_LABEL}</Text><Text style={styles.title}>{record.accountName || EMPTY_VALUE_LABEL}</Text><Text style={styles.subtitle}>{record.email || EMPTY_VALUE_LABEL}</Text>
    <Section title="Account identity" /><View style={styles.card}><Row label="Account name" value={valueOrEmpty(record.accountName)} /><Row label="Email address" value={valueOrEmpty(record.email)} /><Row label="Phone number" value={valueOrEmpty(record.phoneNumber)} />{showMore ? <><Row label="Username" value={valueOrEmpty(record.username)} /><LinkRow label="Primary account link" url={record.accountUrl} onPress={() => openLink(record.accountUrl)} />{(record.links || []).filter(link => link.url !== record.accountUrl).map(link => <LinkRow key={link.id} label={link.label || 'Additional link'} url={link.url} onPress={() => openLink(link.url)} />)}</> : null}</View>
    <Section title="Platform and relationships" /><View style={styles.card}>{platform ? <RelationList label="Platform" values={[{id: platform.id, name: platform.name}]} onPress={onOpenPlatform} /> : <Row label="Platform" value={EMPTY_VALUE_LABEL} />}<Row label="Category" value={valueOrEmpty(category)} /><RelationList label="Projects" values={projects.map(item => ({id: item.id, name: item.name}))} onPress={onOpenProject} /><RelationList label="Clients" values={clients.map(item => ({id: item.id, name: item.name}))} onPress={onOpenClient} /><Row label="Owner" value={valueOrEmpty(record.owner)} /><Row label="Related accounts" value={record.relatedAccountIds?.length ? `${record.relatedAccountIds.length} linked record(s)` : EMPTY_VALUE_LABEL} /></View>
    <Section title="Subscription and billing" /><View style={styles.card}><Row label="Subscription status" value={record.subscriptionStatus === 'notApplicable' ? 'Not applicable' : valueOrEmpty(record.subscriptionStatus)} />{showMore ? <><Row label="Subscription plan" value={valueOrEmpty(record.subscriptionPlan)} /><Row label="Subscription start date" value={valueOrEmpty(record.subscriptionStartDate)} /><Row label="Subscription expiry date" value={valueOrEmpty(record.subscriptionExpiryDate)} /><Row label="Renewal date" value={valueOrEmpty(record.renewalDate)} /><Row label="Billing cycle" value={valueOrEmpty(record.billingCycle)} /><Row label="Payment notes" value={valueOrEmpty(record.paymentNotes)} /></> : null}</View>
    <Section title="Status and review" /><View style={styles.card}><Row label="Account status" value={valueOrEmpty(record.status)} />{showMore ? <><Row label="Priority" value={valueOrEmpty(record.priority)} /><Row label="Added" value={date(record.createdAt)} /><Row label="Last updated" value={date(record.updatedAt)} /><Row label="Last verified" value={date(record.lastVerifiedAt)} /><Row label="Tags" value={record.tags.length ? record.tags.join(', ') : EMPTY_VALUE_LABEL} /></> : null}</View>
    {showMore ? <><Section title="Notes" /><View style={styles.card}><Text style={styles.notes}>{valueOrEmpty(record.notes)}</Text></View><Section title="Sensitive information" /><View style={styles.card}>{record.passwordRef ? <><Row label="Password" value={secret || 'Stored securely'} /><View style={styles.actions}><Pressable style={styles.secondary} onPress={async () => setSecret(secret ? '' : (nativeStore ? await nativeStore.secureLoad(record.passwordRef!) : ''))}><Text style={styles.secondaryText}>{secret ? 'Hide password' : 'Reveal password'}</Text></Pressable>{secret ? <Pressable style={styles.secondary} onPress={() => nativeStore?.setClipboard(secret)}><Text style={styles.secondaryText}>Copy password</Text></Pressable> : null}</View></> : <Row label="Password" value={EMPTY_VALUE_LABEL} />}</View></> : null}
    <Pressable style={styles.showMore} onPress={() => setShowMore(!showMore)}><Text style={styles.showMoreText}>{showMore ? 'Show less' : 'Show more fields'}</Text></Pressable>
    <ContextMenu visible={menuOpen} onClose={() => setMenuOpen(false)} items={[{label: 'Edit account', onPress: onEdit}, {label: record.status === 'paused' ? 'Resume account' : 'Pause account', onPress: () => onUpdate({status: record.status === 'paused' ? 'active' : 'paused'})}, {label: 'Mark verified today', onPress: () => onUpdate({lastVerifiedAt: new Date().toISOString()})}, {label: record.status === 'archived' ? 'Restore record' : 'Archive record', onPress: archiveOrRestore}, {label: 'Delete permanently', destructive: true, onPress: () => Alert.alert('Delete record?', 'This cannot be undone.', [{text: 'Cancel'}, {text: 'Delete', style: 'destructive', onPress: onDelete}])}]} />
  </ScrollView>;
}
function Section({title}: {title: string}) { return <Text style={styles.section}>{title}</Text>; }
function Row({label, value}: {label: string; value: string}) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
function LinkRow({label, url, onPress}: {label: string; url?: string; onPress: () => void}) { return <View style={styles.row}><Text style={styles.label}>{label}</Text>{url ? <Pressable onPress={onPress}><Text style={styles.link}>{url}</Text></Pressable> : <Text style={styles.value}>{EMPTY_VALUE_LABEL}</Text>}</View>; }
function RelationList({label, values, onPress}: {label: string; values: {id: string; name: string}[]; onPress?: (id: string) => void}) { return <View style={styles.row}><Text style={styles.label}>{label}</Text>{values.length ? values.map(value => <Pressable key={value.id} onPress={() => onPress?.(value.id)}><Text style={styles.link}>{value.name}</Text></Pressable>) : <Text style={styles.value}>{EMPTY_VALUE_LABEL}</Text>}</View>; }
const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 50}, header: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, back: {color: '#5267d9', fontWeight: '700'}, moreButton: {width: 42, height: 36, borderRadius: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: '#dce2ec', alignItems: 'center', justifyContent: 'center'}, moreText: {color: '#5267d9', fontWeight: '900', letterSpacing: 2}, eyebrow: {color: '#5267d9', fontWeight: '800', textTransform: 'uppercase', marginTop: 24}, title: {fontSize: 27, fontWeight: '800', color: '#172033', marginTop: 8}, subtitle: {fontSize: 16, color: '#687386', marginTop: 5}, section: {fontSize: 13, fontWeight: '800', color: '#5267d9', textTransform: 'uppercase', letterSpacing: 1, marginTop: 22, marginBottom: 10}, card: {backgroundColor: '#fff', borderRadius: 16, padding: 17, borderWidth: 1, borderColor: '#e2e7f0'}, row: {paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#edf0f4'}, label: {fontSize: 11, color: '#87909c', textTransform: 'uppercase', fontWeight: '800'}, value: {fontSize: 16, color: '#172033', marginTop: 3}, link: {fontSize: 15, color: '#5267d9', marginTop: 3, textDecorationLine: 'underline'}, notes: {color: '#4e596b', lineHeight: 22}, actions: {flexDirection: 'row', gap: 8, marginTop: 10}, secondary: {borderWidth: 1, borderColor: '#dce2ec', borderRadius: 10, padding: 10}, secondaryText: {color: '#5267d9', fontWeight: '700'}, showMore: {borderWidth: 1, borderColor: '#5267d9', borderRadius: 12, padding: 14, alignItems: 'center', marginTop: 18}, showMoreText: {color: '#5267d9', fontWeight: '800'}});
