import React, {useState} from 'react';
import {Alert, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {Category, RegisterData} from '../domain/models';
import {FormField} from '../components/FormField';

export function CategoriesScreen({data, onBack, onSave}: {data: RegisterData; onBack: () => void; onSave: (next: RegisterData) => void}) {
  const [editing, setEditing] = useState<Category>();
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const begin = (category?: Category) => {setEditing(category); setName(category?.name || ''); setDescription(category?.description || '');};
  const save = () => {
    if (!name.trim()) return Alert.alert('Category name required');
    const now = new Date().toISOString();
    const category: Category = {id: editing?.id || `category-${Date.now()}`, name: name.trim(), description: description.trim() || undefined, archived: editing?.archived || false, createdAt: editing?.createdAt || now, updatedAt: now};
    onSave({...data, categories: [...data.categories.filter(item => item.id !== category.id), category]});
    begin();
  };
  const archive = (category: Category) => onSave({...data, categories: data.categories.map(item => item.id === category.id ? {...item, archived: true, updatedAt: new Date().toISOString()} : item)});
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={onBack}><Text style={styles.back}>‹ Filing settings</Text></Pressable><Text style={styles.title}>Categories</Text><Text style={styles.hint}>Organize accounts by the kind of service or work they represent. Categories can be archived without removing account history.</Text><View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'Edit category' : 'Add category'}</Text><FormField label="Name" value={name} placeholder="Example: Cloud services" onChangeText={setName}/><FormField label="Description" value={description} placeholder="Optional filing guidance" onChangeText={setDescription}/><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>{editing ? 'Save changes' : 'Add category'}</Text></Pressable>{editing ? <Pressable style={styles.outline} onPress={() => begin()}><Text style={styles.outlineText}>Cancel edit</Text></Pressable> : null}</View><Text style={styles.section}>Available categories</Text>{data.categories.filter(item => !item.archived).map(category => <View style={styles.row} key={category.id}><View style={styles.flex}><Text style={styles.rowTitle}>{category.name}</Text><Text style={styles.rowMeta}>{category.description || 'No description'} · {data.records.filter(record => record.categoryId === category.id).length} account(s)</Text></View><Pressable onPress={() => begin(category)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => archive(category)}><Text style={styles.archive}>Archive</Text></Pressable></View>)}<Text style={styles.section}>Archived</Text>{data.categories.filter(item => item.archived).map(category => <View style={styles.archivedRow} key={category.id}><Text style={styles.rowTitle}>{category.name}</Text><Text style={styles.rowMeta}>Archived</Text></View>)}</ScrollView>;
}

const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 50}, back: {color: '#5267d9', fontWeight: '700'}, title: {fontSize: 26, fontWeight: '800', color: '#172033', marginVertical: 16}, hint: {color: '#687386', lineHeight: 21}, card: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 16, marginTop: 18}, cardTitle: {fontSize: 17, fontWeight: '800', color: '#172033', marginBottom: 14}, primary: {backgroundColor: '#5267d9', borderRadius: 12, padding: 14, marginTop: 4}, primaryText: {color: '#fff', fontWeight: '800', textAlign: 'center'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 8}, outlineText: {color: '#5267d9', fontWeight: '800'}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, row: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7f0', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10}, archivedRow: {backgroundColor: '#f0f2f6', borderRadius: 13, padding: 14, marginBottom: 8}, flex: {flex: 1}, rowTitle: {color: '#172033', fontWeight: '800'}, rowMeta: {color: '#687386', fontSize: 12, marginTop: 5}, action: {color: '#5267d9', fontWeight: '800'}, archive: {color: '#b34848', fontWeight: '700'}});
