import React, {useState} from 'react';
import {Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {Client, ContactReference, LinkReference, RegisterData} from '../domain/models';
import {FormField} from '../components/FormField';
import {LinksEditor} from '../components/LinksEditor';
import {ContactsEditor} from '../components/ContactsEditor';

export function ClientsScreen({data, onBack, onSave}: {data: RegisterData; onBack: () => void; onSave: (next: RegisterData) => void}) {
  const [editing, setEditing] = useState<Client>(); const [name, setName] = useState(''); const [contacts, setContacts] = useState<ContactReference[]>([]); const [links, setLinks] = useState<LinkReference[]>([]); const [notes, setNotes] = useState('');
  const begin = (client?: Client) => {setEditing(client); setName(client?.name || ''); setContacts(client?.contacts || []); setLinks(client?.links || (client?.websiteUrl ? [{id: `${client.id}-primary`, label: 'Primary link', url: client.websiteUrl, isPrimary: true}] : [])); setNotes(client?.notes || '');};
  const save = () => {if (!name.trim()) return Alert.alert('Client name required'); const now = new Date().toISOString(); const primary = links.find(link => link.isPrimary) || links[0]; const client: Client = {id: editing?.id || `client-${Date.now()}`, name: name.trim(), contacts, links, websiteUrl: primary?.url || undefined, notes: notes.trim(), archived: editing?.archived || false, createdAt: editing?.createdAt || now, updatedAt: now}; onSave({...data, clients: [...data.clients.filter(item => item.id !== client.id), client]}); begin();};
  const archive = (client: Client) => {if (data.records.some(record => record.clientIds?.includes(client.id) || record.clientId === client.id)) return Alert.alert('Reassign accounts first', 'This client still has account records. Reassign them before archiving the client.'); if (data.projects.some(project => project.clientIds?.includes(client.id) || project.clientId === client.id)) return Alert.alert('Reassign projects first', 'This client still has projects. Reassign them before archiving the client.'); onSave({...data, clients: data.clients.map(item => item.id === client.id ? {...item, archived: true, updatedAt: new Date().toISOString()} : item)});};
  const restore = (client: Client) => onSave({...data, clients: data.clients.map(item => item.id === client.id ? {...item, archived: false, updatedAt: new Date().toISOString()} : item)});
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={onBack}><Text style={styles.back}>‹ Filing settings</Text></Pressable><Text style={styles.title}>Clients</Text><Text style={styles.hint}>Clients are optional context. Contact information is the primary supporting information for a client.</Text><View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'Edit client' : 'Add client'}</Text><FormField label="Name" value={name} placeholder="Example: Acme Ltd" onChangeText={setName}/><ContactsEditor contacts={contacts} onChange={setContacts}/><LinksEditor links={links} onChange={setLinks}/><FormField label="Notes" value={notes} placeholder="Optional client notes" multiline onChangeText={setNotes}/><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>{editing ? 'Save changes' : 'Add client'}</Text></Pressable>{editing ? <Pressable style={styles.outline} onPress={() => begin()}><Text style={styles.outlineText}>Cancel edit</Text></Pressable> : null}</View><Text style={styles.section}>Active clients</Text>{data.clients.filter(item => !item.archived).map(client => <View style={styles.row} key={client.id}><View style={styles.flex}><Text style={styles.rowTitle}>{client.name}</Text><Text style={styles.rowMeta}>{data.records.filter(record => record.clientIds?.includes(client.id) || record.clientId === client.id).length} account(s) · {data.projects.filter(project => project.clientIds?.includes(client.id) || project.clientId === client.id).length} project(s)</Text>{(client.contacts || []).filter(contact => contact.value).map(contact => <Text key={contact.id} style={styles.contact}>{contact.label}: {contact.value}</Text>)}{(client.links || []).map(link => <Pressable key={link.id} onPress={() => Linking.openURL(link.url)}><Text style={styles.link}>{link.label || 'Link'}: {link.url}</Text></Pressable>)}</View><Pressable onPress={() => begin(client)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => archive(client)}><Text style={styles.archive}>Archive</Text></Pressable></View>)}<Text style={styles.section}>Archived</Text>{data.clients.filter(item => item.archived).map(client => <View style={styles.archivedRow} key={client.id}><View style={styles.flex}><Text style={styles.rowTitle}>{client.name}</Text><Text style={styles.rowMeta}>Archived</Text></View><Pressable onPress={() => restore(client)}><Text style={styles.action}>Restore</Text></Pressable></View>)}</ScrollView>;
}
const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 50}, back: {color: '#5267d9', fontWeight: '700'}, title: {fontSize: 26, fontWeight: '800', color: '#172033', marginVertical: 16}, hint: {color: '#687386', lineHeight: 21}, card: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 16, marginTop: 18}, cardTitle: {fontSize: 17, fontWeight: '800', color: '#172033', marginBottom: 14}, primary: {backgroundColor: '#5267d9', borderRadius: 12, padding: 14, marginTop: 4}, primaryText: {color: '#fff', fontWeight: '800', textAlign: 'center'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 8}, outlineText: {color: '#5267d9', fontWeight: '800'}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, row: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7f0', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10}, archivedRow: {backgroundColor: '#f0f2f6', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10}, flex: {flex: 1}, rowTitle: {color: '#172033', fontWeight: '800'}, rowMeta: {color: '#687386', fontSize: 12, marginTop: 5}, contact: {color: '#4e596b', fontSize: 12, marginTop: 4}, link: {color: '#5267d9', fontSize: 12, marginTop: 5, textDecorationLine: 'underline'}, action: {color: '#5267d9', fontWeight: '800'}, archive: {color: '#b34848', fontWeight: '700'}});
