import React from 'react';
import {Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {isSubscriptionExpiring, needsVerification, RegisterData} from '../domain/models';

export function DashboardScreen({data, onRecords, onAdd, onSettings}: {data: RegisterData; onRecords: () => void; onAdd: () => void; onSettings: () => void}) {
  const active = data.records.filter(record => record.status === 'active').length;
  const expiring = data.records.filter(record => isSubscriptionExpiring(record)).length;
  const verification = data.records.filter(record => needsVerification(record)).length;
  const categories = data.categories.map(category => ({...category, count: data.records.filter(record => record.categoryId === category.id).length})).filter(category => category.count > 0).sort((a, b) => b.count - a.count).slice(0, 5);
  return <ScrollView contentContainerStyle={styles.page}>
    <Text style={styles.eyebrow}>OFFLINE DIGITAL ACCOUNT REGISTER</Text>
    <View style={styles.header}><View><Text style={styles.title}>AGP</Text><Text style={styles.muted}>Your local reference system for accounts, services, and projects</Text></View><Pressable testID="add-account-button" accessibilityRole="button" style={styles.primarySmall} onPress={onAdd}><Text style={styles.primaryText}>+ Add</Text></Pressable></View>
    <View style={styles.summary}><Text style={styles.number}>{data.records.length}</Text><Text style={styles.summaryLabel}>account records</Text><Text style={styles.summaryMeta}>{active} active · {data.categories.length} categories · {data.platforms.length} platforms</Text></View>
    <Text style={styles.section}>Attention</Text>
    <View style={styles.attentionRow}><Metric label="Expiring soon" value={expiring} tone={expiring ? 'warning' : 'normal'} /><Metric label="Needs verification" value={verification} tone={verification ? 'warning' : 'normal'} /><Metric label="Projects" value={data.projects.length} tone="normal" /></View>
    <Text style={styles.section}>Rooms</Text>
    <Menu title="Account register" description="Browse, search, filter, and open every digital account." onPress={onRecords}/>
    <Menu title="Filing settings" description="Manage reference lists, security, and local data." onPress={onSettings}/>
    {categories.length ? <><Text style={styles.section}>Top categories</Text><View style={styles.categoryBox}>{categories.map(category => <View style={styles.categoryRow} key={category.id}><Text style={styles.categoryName}>{category.name}</Text><Text style={styles.categoryCount}>{category.count}</Text></View>)}</View></> : null}
    <Text style={styles.section}>Quick action</Text>
    <Pressable style={styles.outline} onPress={onAdd}><Text style={styles.outlineText}>Create a new account record</Text></Pressable>
  </ScrollView>;
}

function Metric({label, value, tone}: {label: string; value: number; tone: 'warning' | 'normal'}) { return <View style={[styles.metric, tone === 'warning' && styles.warningMetric]}><Text style={styles.metricNumber}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Menu({title, description, onPress}: {title: string; description: string; onPress: () => void}) { return <Pressable style={styles.menu} onPress={onPress}><View><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDescription}>{description}</Text></View><Text style={styles.chevron}>›</Text></Pressable>; }
const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 36}, eyebrow: {color: '#5267d9', fontSize: 11, fontWeight: '800', letterSpacing: 1.2}, header: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8, marginBottom: 24}, title: {fontSize: 30, fontWeight: '800', color: '#172033'}, muted: {color: '#687386', lineHeight: 21, maxWidth: 280}, primarySmall: {backgroundColor: '#5267d9', paddingHorizontal: 15, paddingVertical: 11, borderRadius: 11}, primaryText: {color: '#fff', fontWeight: '800', textAlign: 'center'}, summary: {backgroundColor: '#5267d9', borderRadius: 18, padding: 20}, number: {fontSize: 38, color: '#fff', fontWeight: '800'}, summaryLabel: {fontSize: 16, color: '#fff', fontWeight: '700'}, summaryMeta: {color: '#dfe4ff', marginTop: 10}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, attentionRow: {flexDirection: 'row', gap: 8}, metric: {flex: 1, backgroundColor: '#fff', borderRadius: 13, borderWidth: 1, borderColor: '#e2e7f0', padding: 12}, warningMetric: {borderColor: '#e8c778', backgroundColor: '#fffaf0'}, metricNumber: {fontSize: 22, fontWeight: '800', color: '#172033'}, metricLabel: {fontSize: 11, color: '#687386', marginTop: 4}, menu: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 17, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between'}, menuTitle: {color: '#172033', fontWeight: '800', fontSize: 16}, menuDescription: {color: '#687386', marginTop: 5, paddingRight: 12}, chevron: {fontSize: 25, color: '#5267d9'}, categoryBox: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', paddingHorizontal: 16}, categoryRow: {paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#edf0f4', flexDirection: 'row', justifyContent: 'space-between'}, categoryName: {color: '#172033'}, categoryCount: {color: '#5267d9', fontWeight: '800'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 14, alignItems: 'center'}, outlineText: {color: '#5267d9', fontWeight: '800'}});
