import React, {useState} from 'react';
import {Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {LinkReference, Project, RegisterData, RecordStatus} from '../domain/models';
import {FormField} from '../components/FormField';
import {SelectField} from '../components/SelectField';
import {isValidUrl} from '../domain/validation';

export function ProjectsScreen({data, onBack, onSave}: {data: RegisterData; onBack: () => void; onSave: (next: RegisterData) => void}) {
  const [editing, setEditing] = useState<Project>();
  const [name, setName] = useState('');
  const [clientId, setClientId] = useState('');
  const [websiteUrl, setWebsiteUrl] = useState('');
  const [testingUrl, setTestingUrl] = useState('');
  const [productionUrl, setProductionUrl] = useState('');
  const [notes, setNotes] = useState('');
  const [status, setStatus] = useState<RecordStatus>('active');
  const begin = (project?: Project) => {setEditing(project); setName(project?.name || ''); setClientId(project?.clientId || ''); setWebsiteUrl(project?.websiteUrl || ''); setTestingUrl(project?.links?.find(link => link.label === 'Testing')?.url || ''); setProductionUrl(project?.links?.find(link => link.label === 'Production')?.url || ''); setNotes(project?.notes || ''); setStatus(project?.status || 'active');};
  const save = () => {
    if (!name.trim()) return Alert.alert('Project name required');
    if (!isValidUrl(websiteUrl) || !isValidUrl(testingUrl) || !isValidUrl(productionUrl)) return Alert.alert('Use valid http or https links');
    const now = new Date().toISOString();
    const links: LinkReference[] = [testingUrl, productionUrl].filter(Boolean).map((url, index) => ({id: `${editing?.id || 'project'}-link-${index}`, label: index === 0 ? 'Testing' : 'Production', url}));
    const project: Project = {id: editing?.id || `project-${Date.now()}`, name: name.trim(), clientId: clientId || undefined, websiteUrl: websiteUrl.trim() || undefined, links, notes: notes.trim(), status, archived: editing?.archived || false, createdAt: editing?.createdAt || now, updatedAt: now};
    onSave({...data, projects: [...data.projects.filter(item => item.id !== project.id), project]});
    begin();
  };
  const archive = (project: Project) => onSave({...data, projects: data.projects.map(item => item.id === project.id ? {...item, archived: true, status: 'archived', updatedAt: new Date().toISOString()} : item)});
  const open = (url?: string) => {if (url) Linking.openURL(url);};
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={onBack}><Text style={styles.back}>‹ Filing settings</Text></Pressable><Text style={styles.title}>Projects</Text><Text style={styles.hint}>Keep websites, applications, client work, repositories, and other activities organized with their working links.</Text><View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'Edit project' : 'Add project'}</Text><FormField label="Project name" value={name} placeholder="Example: Client website" onChangeText={setName}/><SelectField label="Client" value={clientId} options={[{id: '', name: 'No client'}, ...data.clients.filter(item => !item.archived)]} onChange={setClientId}/><FormField label="Primary website link" value={websiteUrl} placeholder="https://..." keyboardType="url" onChangeText={setWebsiteUrl}/><FormField label="Testing link" value={testingUrl} placeholder="https://staging..." keyboardType="url" onChangeText={setTestingUrl}/><FormField label="Production link" value={productionUrl} placeholder="https://production..." keyboardType="url" onChangeText={setProductionUrl}/><SelectField label="Project status" value={status} options={[{id: 'active', name: 'Active'}, {id: 'paused', name: 'Paused'}, {id: 'archived', name: 'Archived'}]} onChange={next => setStatus(next as RecordStatus)}/><FormField label="Notes" value={notes} placeholder="Project reference notes" multiline onChangeText={setNotes}/><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>{editing ? 'Save changes' : 'Add project'}</Text></Pressable>{editing ? <Pressable style={styles.outline} onPress={() => begin()}><Text style={styles.outlineText}>Cancel edit</Text></Pressable> : null}</View><Text style={styles.section}>Active projects</Text>{data.projects.filter(item => !item.archived).map(project => <View style={styles.row} key={project.id}><View style={styles.flex}><Text style={styles.rowTitle}>{project.name}</Text><Text style={styles.rowMeta}>{data.clients.find(client => client.id === project.clientId)?.name || 'No client'} · {data.records.filter(record => record.projectId === project.id).length} account(s)</Text>{project.websiteUrl ? <Pressable onPress={() => open(project.websiteUrl)}><Text style={styles.link}>Primary: {project.websiteUrl}</Text></Pressable> : null}{project.links?.map(link => <Pressable key={link.id} onPress={() => open(link.url)}><Text style={styles.link}>{link.label}: {link.url}</Text></Pressable>)}</View><Pressable onPress={() => begin(project)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => archive(project)}><Text style={styles.archive}>Archive</Text></Pressable></View>)}</ScrollView>;
}

const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 50}, back: {color: '#5267d9', fontWeight: '700'}, title: {fontSize: 26, fontWeight: '800', color: '#172033', marginVertical: 16}, hint: {color: '#687386', lineHeight: 21}, card: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 16, marginTop: 18}, cardTitle: {fontSize: 17, fontWeight: '800', color: '#172033', marginBottom: 14}, primary: {backgroundColor: '#5267d9', borderRadius: 12, padding: 14, marginTop: 4}, primaryText: {color: '#fff', fontWeight: '800', textAlign: 'center'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 8}, outlineText: {color: '#5267d9', fontWeight: '800'}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, row: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7f0', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10}, flex: {flex: 1}, rowTitle: {color: '#172033', fontWeight: '800'}, rowMeta: {color: '#687386', fontSize: 12, marginTop: 5}, link: {color: '#5267d9', fontSize: 12, marginTop: 5, textDecorationLine: 'underline'}, action: {color: '#5267d9', fontWeight: '800'}, archive: {color: '#b34848', fontWeight: '700'}});
