import React, {useState} from 'react';
import {Alert, Linking, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {LinkReference, Project, RegisterData, RecordStatus} from '../domain/models';
import {FormField} from '../components/FormField';
import {SelectField} from '../components/SelectField';
import {LinksEditor} from '../components/LinksEditor';

export function ProjectsScreen({data, onBack, onSave}: {data: RegisterData; onBack: () => void; onSave: (next: RegisterData) => void}) {
  const [editing, setEditing] = useState<Project>();
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [clientId, setClientId] = useState(''); const [links, setLinks] = useState<LinkReference[]>([]); const [notes, setNotes] = useState(''); const [status, setStatus] = useState<RecordStatus>('active');
  const begin = (project?: Project) => {setEditing(project); setName(project?.name || ''); setDescription(project?.description || ''); setClientId(project?.clientId || project?.clientIds?.[0] || ''); setLinks(project?.links || (project?.websiteUrl ? [{id: `${project.id}-primary`, label: 'Primary link', url: project.websiteUrl, isPrimary: true}] : [])); setNotes(project?.notes || ''); setStatus(project?.status || 'active');};
  const save = () => {if (!name.trim()) return Alert.alert('Project name required'); if (!description.trim()) return Alert.alert('Project description required'); const now = new Date().toISOString(); const primary = links.find(link => link.isPrimary) || links[0]; const project: Project = {id: editing?.id || `project-${Date.now()}`, name: name.trim(), description: description.trim(), clientId: clientId || undefined, clientIds: clientId ? [clientId] : [], websiteUrl: primary?.url || undefined, links, notes: notes.trim(), status, archived: editing?.archived || false, createdAt: editing?.createdAt || now, updatedAt: now}; onSave({...data, projects: [...data.projects.filter(item => item.id !== project.id), project]}); begin();};
  const archive = (project: Project) => onSave({...data, projects: data.projects.map(item => item.id === project.id ? {...item, archived: true, status: 'archived', updatedAt: new Date().toISOString()} : item)});
  const open = (url?: string) => {if (url) Linking.openURL(url);};
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={onBack}><Text style={styles.back}>‹ Filing settings</Text></Pressable><Text style={styles.title}>Projects</Text><Text style={styles.hint}>Projects are independent records for websites, campaigns, client work, research, services, or any other activity.</Text><View style={styles.card}><Text style={styles.cardTitle}>{editing ? 'Edit project' : 'Add project'}</Text><FormField label="Project name" value={name} placeholder="Example: Client website" onChangeText={setName}/><FormField label="Description *" value={description} placeholder="What is this project about?" multiline onChangeText={setDescription}/><SelectField label="Client" value={clientId} options={[{id: '', name: 'No client'}, ...data.clients.filter(item => !item.archived)]} onChange={setClientId}/><LinksEditor links={links} onChange={setLinks}/><SelectField label="Project status" value={status} options={[{id: 'active', name: 'Active'}, {id: 'paused', name: 'Paused'}, {id: 'archived', name: 'Archived'}]} onChange={next => setStatus(next as RecordStatus)}/><FormField label="Notes" value={notes} placeholder="Project reference notes" multiline onChangeText={setNotes}/><Pressable style={styles.primary} onPress={save}><Text style={styles.primaryText}>{editing ? 'Save changes' : 'Add project'}</Text></Pressable>{editing ? <Pressable style={styles.outline} onPress={() => begin()}><Text style={styles.outlineText}>Cancel edit</Text></Pressable> : null}</View><Text style={styles.section}>Active projects</Text>{data.projects.filter(item => !item.archived).map(project => <View style={styles.row} key={project.id}><View style={styles.flex}><Text style={styles.rowTitle}>{project.name}</Text><Text style={styles.rowMeta}>{project.description} · {data.clients.find(client => client.id === project.clientId)?.name || 'No client'} · {data.records.filter(record => record.projectId === project.id || record.projectIds?.includes(project.id)).length} account(s)</Text>{(project.links || []).map(link => <Pressable key={link.id} onPress={() => open(link.url)}><Text style={styles.link}>{link.label || 'Link'}: {link.url}</Text></Pressable>)}</View><Pressable onPress={() => begin(project)}><Text style={styles.action}>Edit</Text></Pressable><Pressable onPress={() => archive(project)}><Text style={styles.archive}>Archive</Text></Pressable></View>)}</ScrollView>;
}
const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 50}, back: {color: '#5267d9', fontWeight: '700'}, title: {fontSize: 26, fontWeight: '800', color: '#172033', marginVertical: 16}, hint: {color: '#687386', lineHeight: 21}, card: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 16, marginTop: 18}, cardTitle: {fontSize: 17, fontWeight: '800', color: '#172033', marginBottom: 14}, primary: {backgroundColor: '#5267d9', borderRadius: 12, padding: 14, marginTop: 4}, primaryText: {color: '#fff', fontWeight: '800', textAlign: 'center'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 13, alignItems: 'center', marginTop: 8}, outlineText: {color: '#5267d9', fontWeight: '800'}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, row: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7f0', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 10}, flex: {flex: 1}, rowTitle: {color: '#172033', fontWeight: '800'}, rowMeta: {color: '#687386', fontSize: 12, marginTop: 5}, link: {color: '#5267d9', fontSize: 12, marginTop: 5, textDecorationLine: 'underline'}, action: {color: '#5267d9', fontWeight: '800'}, archive: {color: '#b34848', fontWeight: '700'}});
