import React, {useMemo, useState} from 'react';
import {FlatList, Linking, Pressable, StyleSheet, Text, TextInput, View} from 'react-native';
import {AccountRecord, RegisterData, RecordStatus, SubscriptionStatus} from '../domain/models';
import {filterRecords} from '../domain/filters';
import {SelectField} from '../components/SelectField';

const formatDate = (value: string) => new Date(value).toLocaleDateString([], {day: 'numeric', month: 'short', year: 'numeric'});
const subscriptionNames = [{id: '', name: 'All subscriptions'}, {id: 'active', name: 'Active subscription'}, {id: 'free', name: 'Free plan'}, {id: 'trial', name: 'Trial'}, {id: 'cancelled', name: 'Cancelled'}, {id: 'expired', name: 'Expired'}, {id: 'paused', name: 'Paused'}, {id: 'notApplicable', name: 'Not applicable'}];

export function RegisterScreen({data, onBack, onAdd, onOpen}: {data: RegisterData; onBack: () => void; onAdd: () => void; onOpen: (record: AccountRecord) => void}) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<RecordStatus | 'all'>('active');
  const [subscriptionStatus, setSubscriptionStatus] = useState<SubscriptionStatus | ''>('');
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [clientId, setClientId] = useState('');
  const [platformId, setPlatformId] = useState('');
  const [categoryId, setCategoryId] = useState('');
  const records = useMemo(() => filterRecords(data.records, {query, statuses: status === 'all' ? undefined : [status], subscriptionStatuses: subscriptionStatus ? [subscriptionStatus] : undefined, clientId: clientId || undefined, platformId: platformId || undefined, categoryId: categoryId || undefined}, record => ({
    client: data.clients.filter(item => (record.clientIds || (record.clientId ? [record.clientId] : [])).includes(item.id)).map(item => item.name).join(', ') || 'No client',
    project: data.projects.filter(item => (record.projectIds || (record.projectId ? [record.projectId] : [])).includes(item.id)).map(item => item.name).join(', ') || 'No project',
    platform: data.platforms.find(item => item.id === record.platformId)?.name || 'Other',
    category: data.categories.find(item => item.id === record.categoryId)?.name || 'No category',
  })), [data, query, status, subscriptionStatus, clientId, platformId, categoryId]);
  const labels = (record: AccountRecord) => ({client: data.clients.filter(item => (record.clientIds || (record.clientId ? [record.clientId] : [])).includes(item.id)).map(item => item.name).join(', ') || 'No client', project: data.projects.filter(item => (record.projectIds || (record.projectId ? [record.projectId] : [])).includes(item.id)).map(item => item.name).join(', ') || 'No project', platform: data.platforms.find(item => item.id === record.platformId)?.name || 'Other', category: data.categories.find(item => item.id === record.categoryId)?.name || 'No category'});
  return <View style={styles.root}>
    <View style={styles.topBar}><Pressable onPress={onBack}><Text style={styles.back}>‹ Dashboard</Text></Pressable><Pressable style={styles.primarySmall} onPress={onAdd}><Text style={styles.primaryText}>+ Add</Text></Pressable></View>
    <Text style={styles.title}>Account register</Text>
    <Text style={styles.subtitle}>Search and file every digital account, service, and subscription.</Text>
    <TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Search names, emails, platforms, projects..." placeholderTextColor="#87909c" />
    <View style={styles.toolbar}><Pressable style={styles.toolbarButton} onPress={() => setFiltersOpen(!filtersOpen)}><Text style={styles.toolbarText}>{filtersOpen ? 'Hide filters' : 'Filters'}</Text></Pressable><View style={styles.statusSelect}><SelectField label="Account status" value={status} options={[{id: 'all', name: 'All accounts'}, {id: 'active', name: 'Active'}, {id: 'paused', name: 'Paused'}, {id: 'suspended', name: 'Suspended'}, {id: 'archived', name: 'Archived'}, {id: 'closed', name: 'Closed'}]} onChange={value => setStatus(value as RecordStatus | 'all')} /></View></View>
    {filtersOpen ? <View style={styles.filterBox}><SelectField label="Platform" value={platformId} options={[{id: '', name: 'All platforms'}, ...data.platforms.filter(item => !item.archived)]} onChange={setPlatformId}/><SelectField label="Category" value={categoryId} options={[{id: '', name: 'All categories'}, ...data.categories.filter(item => !item.archived)]} onChange={setCategoryId}/><SelectField label="Client" value={clientId} options={[{id: '', name: 'All clients'}, ...data.clients.filter(item => !item.archived)]} onChange={setClientId}/><SelectField label="Subscription" value={subscriptionStatus} options={subscriptionNames} onChange={value => setSubscriptionStatus(value as SubscriptionStatus | '')}/></View> : null}
    <Text style={styles.count}>{records.length} record{records.length === 1 ? '' : 's'}</Text>
    <FlatList data={records} keyExtractor={item => item.id} contentContainerStyle={styles.list} renderItem={({item}) => {const name = labels(item); return <Pressable style={styles.card} onPress={() => onOpen(item)}><View style={styles.cardHeader}><View style={styles.flex}><Text style={styles.account}>{item.accountName || 'Unnamed account'}</Text><Text style={styles.email}>{item.email || 'Email not provided'}</Text></View><Text style={[styles.badge, item.status === 'archived' && styles.archivedBadge]}>{item.status}</Text></View><View style={styles.context}><Text style={styles.platform}>{name.platform}</Text><Text style={styles.contextText}>{name.category}</Text></View><Text style={styles.meta}>{name.project} · {name.client}</Text><View style={styles.footer}><Text style={styles.subscription}>{item.subscriptionStatus || 'not applicable'}</Text><Text style={styles.updated}>Updated {formatDate(item.updatedAt)}</Text></View>{item.accountUrl ? <Pressable style={styles.linkButton} onPress={async event => {event.stopPropagation(); if (await Linking.canOpenURL(item.accountUrl!)) await Linking.openURL(item.accountUrl!);}}><Text style={styles.linkText}>Open account link</Text></Pressable> : null}</Pressable>;}} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>No records match this view</Text><Text style={styles.muted}>Add an account or adjust the search and filing filters.</Text></View>}/>
  </View>;
}

const styles = StyleSheet.create({root: {flex: 1, padding: 20}, topBar: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, back: {color: '#5267d9', fontWeight: '700'}, primarySmall: {backgroundColor: '#5267d9', paddingHorizontal: 15, paddingVertical: 11, borderRadius: 11}, primaryText: {color: '#fff', fontWeight: '800'}, title: {fontSize: 25, fontWeight: '800', color: '#172033', marginTop: 16}, subtitle: {color: '#687386', lineHeight: 21, marginTop: 5, marginBottom: 12}, search: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e0e5ee', borderRadius: 12, padding: 13, fontSize: 15}, toolbar: {flexDirection: 'row', gap: 8, alignItems: 'center', marginVertical: 10}, toolbarButton: {borderWidth: 1, borderColor: '#dce2ec', backgroundColor: '#fff', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 9}, toolbarText: {color: '#5267d9', fontWeight: '700'}, statusSelect: {flex: 1}, filterBox: {backgroundColor: '#eef1f8', padding: 12, borderRadius: 12}, count: {color: '#687386', marginBottom: 8}, list: {paddingBottom: 28}, card: {backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e2e7f0', padding: 16, marginBottom: 10}, cardHeader: {flexDirection: 'row'}, flex: {flex: 1}, account: {fontSize: 18, fontWeight: '800', color: '#172033'}, email: {color: '#4e596b', marginTop: 4}, badge: {color: '#287a51', backgroundColor: '#e5f5ec', padding: 6, borderRadius: 14, fontSize: 11, alignSelf: 'flex-start'}, archivedBadge: {color: '#687386', backgroundColor: '#edf0f4'}, context: {flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 12}, platform: {color: '#5267d9', fontWeight: '800', fontSize: 12, textTransform: 'uppercase'}, contextText: {color: '#687386', fontSize: 12}, meta: {color: '#4e596b', marginTop: 8}, footer: {flexDirection: 'row', justifyContent: 'space-between', marginTop: 9}, subscription: {color: '#687386', fontSize: 12, textTransform: 'capitalize'}, updated: {color: '#87909c', fontSize: 11}, linkButton: {marginTop: 12, alignSelf: 'flex-start'}, linkText: {color: '#5267d9', fontWeight: '700', textDecorationLine: 'underline'}, empty: {alignItems: 'center', paddingVertical: 60}, emptyTitle: {fontWeight: '800', color: '#172033', marginBottom: 6}, muted: {color: '#687386', lineHeight: 21, textAlign: 'center'}});
