import React, {useState} from 'react';
import {Alert, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {RegisterData} from '../domain/models';
import {FormField} from '../components/FormField';

export function SettingsScreen({data, hasPin, onBack, onSetPin, onCategories, onPlatforms, onProjects}: {data: RegisterData; hasPin: boolean; onBack: () => void; onSetPin: (value: string) => void; onCategories: () => void; onPlatforms: () => void; onProjects: () => void}) {
  const [pin, setPin] = useState('');
  return <ScrollView contentContainerStyle={styles.page}><Pressable onPress={onBack}><Text style={styles.back}>‹ Dashboard</Text></Pressable><Text style={styles.title}>Filing settings</Text><Text style={styles.hint}>Administration stays separate from the daily register.</Text><Text style={styles.section}>Reference lists</Text><Text style={styles.info}>{data.categories.length} categories · {data.platforms.length} platforms · {data.projects.length} projects · {data.clients.length} clients</Text><Text style={styles.muted}>Customize the filing vocabulary without changing existing account records.</Text><View style={styles.menuGroup}><Menu title="Manage categories" description="Create, rename, and archive account categories." onPress={onCategories}/><Menu title="Manage platforms" description="Add services, assign categories, and save website links." onPress={onPlatforms}/><Menu title="Manage projects" description="Track projects with primary, testing, and production links." onPress={onProjects}/></View><Text style={styles.section}>Security</Text><Text style={styles.muted}>{hasPin ? 'A local PIN protects the register when you leave the app.' : 'Add a local PIN to protect the register.'}</Text><FormField label="PIN" value={pin} placeholder="At least 4 digits" onChangeText={setPin} keyboardType="number-pad" secureTextEntry/><Pressable style={styles.primary} onPress={() => {if (pin && pin.length < 4) return Alert.alert('PIN too short', 'Use at least 4 digits.'); onSetPin(pin);}}><Text style={styles.primaryText}>{hasPin ? 'Update PIN' : 'Set PIN'}</Text></Pressable>{hasPin ? <Pressable style={styles.outline} onPress={() => onSetPin('')}><Text style={styles.outlineText}>Remove PIN</Text></Pressable> : null}<Text style={styles.section}>Data</Text><Text style={styles.muted}>Records remain stored locally on this device. Backup and restore remains a separate workflow.</Text></ScrollView>;
}

function Menu({title, description, onPress}: {title: string; description: string; onPress: () => void}) { return <Pressable style={styles.menu} onPress={onPress}><View style={styles.flex}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuDescription}>{description}</Text></View><Text style={styles.chevron}>›</Text></Pressable>; }
const styles = StyleSheet.create({page: {padding: 20, paddingBottom: 45}, back: {color: '#5267d9', fontWeight: '700'}, title: {fontSize: 25, fontWeight: '800', color: '#172033', marginVertical: 16}, hint: {color: '#687386'}, section: {fontSize: 13, fontWeight: '800', color: '#687386', textTransform: 'uppercase', letterSpacing: 1, marginTop: 24, marginBottom: 8}, info: {fontSize: 19, fontWeight: '800', color: '#172033', marginBottom: 8}, muted: {color: '#687386', lineHeight: 21}, menuGroup: {marginTop: 14}, menu: {backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#e2e7f0', padding: 15, marginBottom: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'}, flex: {flex: 1}, menuTitle: {color: '#172033', fontWeight: '800', fontSize: 16}, menuDescription: {color: '#687386', marginTop: 4}, chevron: {fontSize: 25, color: '#5267d9'}, primary: {backgroundColor: '#5267d9', borderRadius: 12, padding: 15, marginVertical: 8}, primaryText: {color: '#fff', textAlign: 'center', fontWeight: '800'}, outline: {borderWidth: 1, borderColor: '#cbd3e0', borderRadius: 12, padding: 14, alignItems: 'center'}, outlineText: {color: '#5267d9', fontWeight: '800'}});
