import React, {useMemo, useState} from 'react';
import {FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View} from 'react-native';
export type AssociationOption = {id: string; title: string; subtitle?: string; searchText?: string};
type Props = {visible: boolean; title: string; options: AssociationOption[]; selectedIds: string[]; onCancel: () => void; onSave: (ids: string[]) => void};
export function AssociationPicker({visible, title, options, selectedIds, onCancel, onSave}: Props) {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState<string[]>(selectedIds);
  const filtered = useMemo(() => {const term = query.trim().toLowerCase(); return term ? options.filter(option => `${option.title} ${option.subtitle || ''} ${option.searchText || ''}`.toLowerCase().includes(term)) : options;}, [options, query]);
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  return <Modal visible={visible} animationType="slide" onRequestClose={onCancel}><View style={styles.page}><View style={styles.header}><Pressable onPress={onCancel}><Text style={styles.cancel}>Cancel</Text></Pressable><Text style={styles.title}>{title}</Text><Pressable onPress={() => onSave(selected)}><Text style={styles.save}>Save</Text></Pressable></View><TextInput style={styles.search} value={query} onChangeText={setQuery} placeholder="Filter by name, email, platform, or category" placeholderTextColor="#87909c"/><Text style={styles.count}>{selected.length} selected</Text><FlatList data={filtered} keyExtractor={item => item.id} renderItem={({item}) => {const checked = selected.includes(item.id); return <Pressable style={styles.row} onPress={() => toggle(item.id)}><View style={[styles.checkbox, checked && styles.checked]}>{checked ? <Text style={styles.tick}>✓</Text> : null}</View><View style={styles.flex}><Text style={styles.rowTitle}>{item.title}</Text>{item.subtitle ? <Text style={styles.subtitle}>{item.subtitle}</Text> : null}</View></Pressable>;}} ListEmptyComponent={<Text style={styles.empty}>No matching records.</Text>}/></View></Modal>;
}
const styles = StyleSheet.create({page: {flex: 1, backgroundColor: '#f5f7fb', padding: 20, paddingTop: 55}, header: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18}, title: {fontSize: 18, fontWeight: '800', color: '#172033'}, cancel: {color: '#687386', fontWeight: '700'}, save: {color: '#5267d9', fontWeight: '800'}, search: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e0e5ee', borderRadius: 12, padding: 13, fontSize: 15}, count: {color: '#687386', marginVertical: 12}, row: {backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e7f0', borderRadius: 13, padding: 14, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 12}, checkbox: {width: 24, height: 24, borderRadius: 7, borderWidth: 1, borderColor: '#b8c2d2', alignItems: 'center', justifyContent: 'center'}, checked: {backgroundColor: '#5267d9', borderColor: '#5267d9'}, tick: {color: '#fff', fontWeight: '800'}, flex: {flex: 1}, rowTitle: {color: '#172033', fontWeight: '800'}, subtitle: {color: '#687386', marginTop: 4, fontSize: 12}, empty: {color: '#687386', textAlign: 'center', padding: 30}});
